### ISSUE TITLE
Width and Height block settings tracking issue

### ISSUE THREAD

**Issue by chrishbite** [bigbite/image-comparison#32]
## Description

Tracking issue for the below items as there will be a significant overlap between the required code changes for each item.

- [ ] https://github.com/bigbite/image-comparison/issues/28
- [ ] https://github.com/bigbite/image-comparison/issues/29
- [ ] https://github.com/bigbite/image-comparison/issues/31

**Comment by g-elwell** [comment]
Thanks for reporting these @chrishbite - we've been looking at how to address the issues on our project board and I was wondering if `there will be a significant overlap between the required code changes for each item` means that the issues can't be picked up individually? If so, should we collate them here to be worked on as one issue?

**Comment by chrishbite** [comment]
> Thanks for reporting these @chrishbite - we've been looking at how to address the issues on our project board and I was wondering if `there will be a significant overlap between the required code changes for each item` means that the issues can't be picked up individually? If so, should we collate them here to be worked on as one issue?

Hey @g-elwell yeah I'd recommend that these are picked up together and worked on simultaneously if possible, as I have a feeling code changes for each are going to be in the same locations/lines and have an effect on the other. With that in mind I created this overarching tracking issue to be assigned and reflect the relation of the issues, this issue should be able to control them by checking/unchecking the issues in the above description.

That being said, the issues could still be worked on individually and then we can deal with the conflicts/overlaps when it comes to merging to a release but I think this option will be less efficient due to duplicates in the potential needed changes.

**Comment by g-elwell** [comment]
> > Thanks for reporting these @chrishbite - we've been looking at how to address the issues on our project board and I was wondering if `there will be a significant overlap between the required code changes for each item` means that the issues can't be picked up individually? If so, should we collate them here to be worked on as one issue?
> 
> Hey @g-elwell yeah I'd recommend that these are picked up together and worked on simultaneously if possible, as I have a feeling code changes for each are going to be in the same locations/lines and have an effect on the other. With that in mind I created this overarching tracking issue to be assigned and reflect the relation of the issues, this issue should be able to control them by checking/unchecking the issues in the above description.
> 
> That being said, the issues could still be worked on individually and then we can deal with the conflicts/overlaps when it comes to merging to a release but I think this option will be less efficient due to duplicates in the potential needed changes.

cool, thanks for the explanation, we'll add this issue to the internal projects board rather than all 4 👍

**Comment by PaulREnglish** [comment]
PR https://github.com/bigbite/image-comparison/pull/39 should fix all these issues but I haven't had time to address the feedback.  I've unassigned myself from the ticket so other people are free to work on this.
